// ─── App ──────────────────────────────────────────────────────────────────────
export const APP_NAME = "Devnandan Interiors";
export const APP_TAGLINE = "Transforming Spaces with Precision 3D Design";
export const APP_VERSION = "1.0.0";

// ─── API ──────────────────────────────────────────────────────────────────────
export const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || "";

// ─── Contact ──────────────────────────────────────────────────────────────────
export const CONTACT_EMAIL = "devnandan3d@gmail.com";
export const CONTACT_PHONE = "085116 98769";
export const ADDRESS = "H/ 1402, Orchid Blues Rd, near Applewood, Nandanbag Society, Ullaria, Bopal, Shela, Ahmedabad, Gujarat 380057";
export const GOOGLE_MAPS_LINK = "https://maps.app.goo.gl/gbKAkH76AQcjLdw7A";
export const WORKING_HOURS = "Mon – Sat: 10:00 AM – 7:00 PM";

// ─── Social ───────────────────────────────────────────────────────────────────
export const SOCIAL_LINKS = {
  instagram: "https://www.instagram.com/devnandan_interiors_90/",
  youtube: "https://www.youtube.com/@devnandaninteriors2748",
  facebook: "https://www.facebook.com/devnandaninteriors90/",
  whatsapp: "https://wa.me/919099011688",
  linkedin: "https://www.linkedin.com/in/devnandan-interiors-238927243/",
  indiamart: "https://www.indiamart.com/devnandan-interiors/",
};

// ─── Navigation ───────────────────────────────────────────────────────────────
export const NAV_LINKS = [
  { label: "Home", path: "/" },
  { label: "About", path: "/about" },
  { label: "Services", path: "/services" },
  { label: "Portfolio", path: "/portfolio" },
  { label: "Contact", path: "/contact" },
];

// ─── About ────────────────────────────────────────────────────────────────────
export const ABOUT_SUMMARY =
  "At Devnandan Interiors, we bridge imagination and reality through precision 3D design. Founded in Ahmedabad, our team of passionate designers and visualizers craft spaces that reflect your personality, lifestyle, and aspirations — before construction begins.";

export const ABOUT_STORY =
  "With over 8 years of experience in interior design and architectural visualization, Devnandan Interiors has become one of Gujarat's most trusted design studios. We specialize in photorealistic 3D renders, animated walkthroughs, modular furniture design, and end-to-end interior consulting for residential and commercial spaces. Every project begins with listening — understanding your vision, your needs, and your budget — and ends with a space that genuinely feels like home.";

export const COMPANY_VALUES = [
  { title: "Precision", description: "Every detail matters. We design with accuracy that translates perfectly from render to reality." },
  { title: "Innovation", description: "We stay ahead of design trends and 3D technology to deliver cutting-edge visuals." },
  { title: "Transparency", description: "No surprises. You see exactly what you're getting before any work begins." },
  { title: "Client-First", description: "Your vision drives every decision we make, from concept to final delivery." },
];

// ─── Services ─────────────────────────────────────────────────────────────────
export const SERVICES = [
  {
    id: "3d-visualization",
    title: "3D Visualization",
    description: "Photorealistic renders of interior spaces before construction begins.",
    longDescription: "Our 3D visualization service delivers stunning, photorealistic renders that let you walk through your space virtually before a single wall goes up. We create detailed renders of every room, capturing lighting, materials, textures, and furniture with pixel-perfect accuracy.",
    image: "/Website/Interior/HD 3d/HD 2/No WM/Big Livingroom view 1.png",
    features: ["Photorealistic rendering", "Multiple view angles", "Material & finish options", "Fast turnaround"],
  },
  {
    id: "interior-design",
    title: "Interior Design",
    description: "End-to-end interior design solutions tailored to your lifestyle and taste.",
    longDescription: "From space planning to furniture selection and material specification, our interior design service covers every aspect of creating a beautiful, functional space. We work with you through each stage, presenting options as 3D visuals so decisions are always clear.",
    image: "/Website/Interior/3d 9/Living Room.jpg",
    features: ["Space planning", "Furniture layout", "Material specification", "Lighting design"],
  },
  {
    id: "space-planning",
    title: "Space Planning",
    description: "Optimized floor plans and furniture layouts for functional, beautiful spaces.",
    longDescription: "Good design starts with a great plan. Our space planning service analyzes your floor plan and creates optimized layouts that maximize functionality, traffic flow, and aesthetics — all visualized in 3D before implementation.",
    image: "/Website/Interior/Floor Plan/6.png",
    features: ["Floor plan analysis", "Furniture placement", "Traffic flow optimization", "3D floor plan views"],
  },
  {
    id: "walkthrough",
    title: "3D Walkthrough",
    description: "Immersive animated walkthroughs to experience your space before it's built.",
    longDescription: "Take a cinematic tour of your future space with our 3D walkthrough animations. These immersive videos let you move through rooms, experience the scale of spaces, and understand how light moves through your home — long before construction begins.",
    image: "/Website/Interior/HD 3d/HD 2/No WM/Small Livingroom view 1.png",
    features: ["Cinematic animation", "Realistic lighting", "Full HD render", "Multiple formats"],
  },
  {
    id: "modular-design",
    title: "Modular Furniture Design",
    description: "Custom modular kitchen, wardrobe, and furniture design with 3D previews.",
    longDescription: "We design bespoke modular kitchens, wardrobes, TV units, study tables, and more — all visualized in 3D with your exact dimensions, finishes, and hardware choices. See it before you build it.",
    image: "/Website/Interior/HD 3d/HD 2/No WM/Kitchen view 1.png",
    features: ["Custom dimensions", "Material & finish selection", "Hardware visualization", "Manufacturing-ready design"],
  },
  {
    id: "renovation",
    title: "Renovation Consulting",
    description: "Expert guidance on redesigning and renovating existing spaces.",
    longDescription: "Planning a renovation? Our consulting service helps you visualize the transformation of your existing space. We create before-and-after 3D renders, advise on structural changes, and provide a clear roadmap from current state to dream space.",
    image: "/Website/Interior/3d 3/Drawing_v1.jpg",
    features: ["Before & after renders", "Structural advice", "Budget planning", "Contractor coordination support"],
  },
];

// ─── Portfolio ────────────────────────────────────────────────────────────────
export const PORTFOLIO_CATEGORIES = [
  { id: "all", label: "All" },
  { id: "residential", label: "Residential" },
  { id: "kitchen", label: "Kitchen" },
  { id: "bedroom", label: "Bedroom" },
  { id: "bathroom", label: "Bathroom" },
  { id: "office", label: "Office" },
  { id: "commercial", label: "Commercial" },
  { id: "exterior", label: "Exterior" },
];

export const PORTFOLIO_ITEMS = [
  // Residential
  { id: 1, title: "Grand Living Room", category: "residential", image: "/Website/Interior/HD 3d/HD 2/No WM/Big Livingroom view 1.png", description: "Spacious living room with premium finishes." },
  { id: 2, title: "Contemporary Living", category: "residential", image: "/Website/Interior/HD 3d/HD 2/No WM/Big Livingroom view 2.png", description: "Modern design with warm lighting and elegant furniture." },
  { id: 3, title: "Compact Living Space", category: "residential", image: "/Website/Interior/HD 3d/HD 2/No WM/Small Livingroom view 1.png", description: "Smart space planning for compact apartment living." },
  { id: 4, title: "Drawing Room Design", category: "residential", image: "/Website/Interior/3d 3/Drawing_v1.jpg", description: "Classic drawing room with contemporary styling." },
  { id: 5, title: "Open Plan Living", category: "residential", image: "/Website/Interior/3d 4/Living room View 1.jpg", description: "Seamless open-plan living with curated lighting." },
  { id: 6, title: "Elegant Living Room", category: "residential", image: "/Website/Interior/3d 9/Living Room.jpg", description: "Luxurious living with statement furniture and art." },
  { id: 7, title: "Foyer Design", category: "residential", image: "/Website/Interior/HD 3d/HD 2/No WM/Foyer area view 1.png", description: "Welcoming foyer that sets the tone for the entire home." },
  { id: 8, title: "Dining Area", category: "residential", image: "/Website/Interior/3d 9/Daining 01.jpg", description: "Elegant dining space with ambient lighting." },

  // Kitchen
  { id: 9, title: "Premium Kitchen", category: "kitchen", image: "/Website/Interior/HD 3d/HD 2/No WM/Kitchen view 1.png", description: "Contemporary kitchen with premium cabinetry." },
  { id: 10, title: "Kitchen & Dining", category: "kitchen", image: "/Website/Interior/HD 3d/HD 2/No WM/Dinning & Kitchen view 1.png", description: "Open kitchen-dining concept with island seating." },
  { id: 11, title: "Minimal Kitchen", category: "kitchen", image: "/Website/Interior/3d 3/kitchen V1.jpg", description: "Clean-line kitchen with integrated appliances." },
  { id: 12, title: "Modular Kitchen", category: "kitchen", image: "/Website/Interior/3d 4/Kitchen view 1.jpg", description: "Space-efficient modular kitchen with smart storage." },
  { id: 13, title: "Classic Kitchen", category: "kitchen", image: "/Website/Interior/3d 9/Kitchen.jpg", description: "Traditional kitchen design with modern amenities." },

  // Bedroom
  { id: 14, title: "Master Bedroom Suite", category: "bedroom", image: "/Website/Interior/3d 3/Master room_V1.jpg", description: "Luxurious master bedroom with custom wardrobe." },
  { id: 15, title: "Daughter's Bedroom", category: "bedroom", image: "/Website/Interior/3d 3/Daughter room_v1.jpg", description: "Elegant bedroom tailored for young adults." },
  { id: 16, title: "Premium Bedroom", category: "bedroom", image: "/Website/Interior/3d 4/Master room view 01.jpg", description: "Premium bedroom with layered lighting." },
  { id: 17, title: "Cozy Bedroom", category: "bedroom", image: "/Website/Interior/3d 8/Bed 1 view 1.jpg", description: "Warm and inviting bedroom with curated details." },
  { id: 18, title: "Kids Bedroom", category: "bedroom", image: "/Website/Interior/WM 3d 9/Kids bedroom View 1.jpg", description: "Fun and functional bedroom for children." },

  // Bathroom
  { id: 19, title: "Master Bathroom", category: "bathroom", image: "/Website/Interior/Bathroom 3d/New WM Bathroom/master bathroom v1.jpg", description: "Spa-inspired master bathroom with premium fixtures." },
  { id: 20, title: "Elegant Bathroom", category: "bathroom", image: "/Website/Interior/Bathroom 3d/New WM Bathroom/parents bathroom v1.jpg", description: "Sophisticated bathroom with marble finishes." },
  { id: 21, title: "Modern Bathroom", category: "bathroom", image: "/Website/Interior/Bathroom 3d/New WM Bathroom/son bathroom v1.jpg", description: "Contemporary bathroom with clean lines." },
  { id: 22, title: "Compact Bathroom", category: "bathroom", image: "/Website/Interior/Bathroom 3d/New WM Bathroom/master bathroom v2.jpg", description: "Smart design for compact bathroom spaces." },

  // Office
  { id: 23, title: "Executive Cabin", category: "office", image: "/Website/Interior/Office 3d/240 cabin 1 view 1.jpg", description: "Premium executive cabin with sophisticated design." },
  { id: 24, title: "Conference Room", category: "office", image: "/Website/Interior/Office 3d/240 conferenceroom view 1.jpg", description: "Modern conference room for productivity." },
  { id: 25, title: "Office Entry", category: "office", image: "/Website/Interior/Office 3d/240 entry view.jpg", description: "Welcoming office reception and entry." },
  { id: 26, title: "Open Office", category: "office", image: "/Website/Interior/Office 3d 2/IMG_3257.jpg", description: "Collaborative open office with ergonomic layout." },

  // Commercial
  { id: 27, title: "Jewellery Showroom", category: "commercial", image: "/Website/Interior/Jewellery Showroom/Gujarat Jewellers view 1.jpg", description: "Elegant showroom with luxury display design." },
  { id: 28, title: "Restaurant Interior", category: "commercial", image: "/Website/Interior/Restaurant 3d/Hocco_View01-2.jpg", description: "Ambient restaurant interior with warm lighting." },
  { id: 29, title: "Rooftop Restaurant", category: "commercial", image: "/Website/Interior/Resataurant Rooftop/34.png", description: "Outdoor rooftop dining with panoramic views." },
  { id: 30, title: "Garment Showroom", category: "commercial", image: "/Website/Interior/Showroom 3d/234 Garment showroom view 1.jpg", description: "Stylish showroom with strategic product display." },
  { id: 31, title: "Salon Interior", category: "commercial", image: "/Website/Interior/Salon/WM Salon (2).jpg", description: "Modern salon with sleek styling stations." },

  // Exterior
  { id: 32, title: "Commercial Facade", category: "exterior", image: "/Website/Exterior/Commercial Building/day view effects.jpg", description: "Contemporary commercial building facade." },
  { id: 33, title: "Apartment Complex", category: "exterior", image: "/Website/Exterior/Commercial Building 2/1.png", description: "Residential apartment with modern exterior." },
  { id: 34, title: "University Campus", category: "exterior", image: "/Website/Exterior/University/view 1.jpg", description: "Educational campus with functional landscaping." },
  { id: 35, title: "Township Development", category: "exterior", image: "/Website/Exterior/Township/site presentation (1).jpg", description: "Master-planned township with integrated amenities." },
  { id: 36, title: "Night View", category: "exterior", image: "/Website/Exterior/Commercial Building/front side night view.jpg", description: "Dramatic commercial building night-time render." },

  // Residential (additional)
  { id: 37, title: "Interior Living Space", category: "residential", image: "/Website/Interior/3d 2/Interiors (3).jpg", description: "Beautifully curated interior living space with warm tones." },
  { id: 38, title: "Modern Interior Design", category: "residential", image: "/Website/Interior/3d 2/Interiors (9).jpg", description: "Modern interior design with clean lines and premium finishes." },
  { id: 39, title: "Contemporary Living Room", category: "residential", image: "/Website/Interior/3d 2/Interiors (10).jpg", description: "Contemporary living room with layered lighting and stylish decor." },
  { id: 40, title: "Elegant Interior", category: "residential", image: "/Website/Interior/3d 2/Interiors (11).jpg", description: "Elegant interior with refined material palette and cohesive design." },
  { id: 41, title: "Stylish Living Area", category: "residential", image: "/Website/Interior/3d 2/Interiors (12).jpg", description: "Stylish living area with curated furniture and accent lighting." },
  { id: 42, title: "Premium Interior Space", category: "residential", image: "/Website/Interior/3d 2/Interiors (35).jpg", description: "Premium interior space showcasing luxury finishes and custom joinery." },
  { id: 43, title: "Designer Living Room", category: "residential", image: "/Website/Interior/3d 2/Interiors (36).jpg", description: "Designer living room with bespoke furniture and statement pieces." },
  { id: 44, title: "Curated Interior", category: "residential", image: "/Website/Interior/3d 2/Interiors (44).jpg", description: "Thoughtfully curated interior with balanced proportions and textures." },
  { id: 45, title: "Refined Living Space", category: "residential", image: "/Website/Interior/3d 2/Interiors (45).jpg", description: "Refined living space with sophisticated color scheme and detailing." },
  { id: 46, title: "Drawing Room Design 2", category: "residential", image: "/Website/Interior/3d 3/Drawing_v2.jpg", description: "Drawing room design with classic contemporary styling." },
  { id: 47, title: "Drawing Room Design 3", category: "residential", image: "/Website/Interior/3d 3/Drawing_v3.jpg", description: "Drawing room with refined furnishings and elegant proportions." },
  { id: 48, title: "Drawing Room Design 4", category: "residential", image: "/Website/Interior/3d 3/Drawing_v4.jpg", description: "Drawing room featuring layered lighting and premium upholstery." },
  { id: 49, title: "Drawing Room View 1", category: "residential", image: "/Website/Interior/3d 4/Drawing room View 01.jpg", description: "Spacious drawing room with a warm and welcoming atmosphere." },
  { id: 50, title: "Drawing Room View 2", category: "residential", image: "/Website/Interior/3d 4/Drawing room View 02.jpg", description: "Drawing room with statement sofa and accent wall design." },
  { id: 51, title: "Open Plan Living 2", category: "residential", image: "/Website/Interior/3d 4/Living room View 2.jpg", description: "Open-plan living with fluid transitions between zones." },
  { id: 52, title: "Open Plan Living 3", category: "residential", image: "/Website/Interior/3d 4/Living room View 3.jpg", description: "Open-plan living area with natural light and modern furniture." },
  { id: 53, title: "Residential Interior 1", category: "residential", image: "/Website/Interior/3d 7/1 (1).jpg", description: "Residential interior with harmonious design and quality finishes." },
  { id: 54, title: "Residential Interior 2", category: "residential", image: "/Website/Interior/3d 7/1 (2).jpg", description: "Residential interior featuring elegant furniture and ambient lighting." },
  { id: 55, title: "Residential Interior 3", category: "residential", image: "/Website/Interior/3d 7/1 (3).jpg", description: "Residential interior with tailored joinery and refined material choices." },
  { id: 56, title: "Residential Interior 4", category: "residential", image: "/Website/Interior/3d 7/1 (4).jpg", description: "Residential interior with balanced composition and premium finishes." },
  { id: 57, title: "Residential Interior 5", category: "residential", image: "/Website/Interior/3d 7/1 (5).jpg", description: "Residential interior showcasing cohesive design and skilled craftsmanship." },
  { id: 58, title: "Residential Interior 6", category: "residential", image: "/Website/Interior/3d 7/1 (6).jpg", description: "Residential interior with curated decor and thoughtful space planning." },
  { id: 59, title: "Residential Interior 7", category: "residential", image: "/Website/Interior/3d 7/1 (7).jpg", description: "Residential interior with elegant proportions and layered textures." },
  { id: 60, title: "Residential Interior 8", category: "residential", image: "/Website/Interior/3d 7/1 (8).jpg", description: "Residential interior featuring warm tones and statement lighting." },
  { id: 61, title: "Residential Interior 9", category: "residential", image: "/Website/Interior/3d 7/1 (9).jpg", description: "Residential interior with modern aesthetic and quality materials." },
  { id: 62, title: "Residential Interior 10", category: "residential", image: "/Website/Interior/3d 7/1 (10).jpg", description: "Residential interior with sophisticated color palette and bespoke furniture." },
  { id: 63, title: "Residential Interior 11", category: "residential", image: "/Website/Interior/3d 7/1 (11).jpg", description: "Residential interior combining comfort and contemporary style." },
  { id: 64, title: "Living Area Design", category: "residential", image: "/Website/Interior/3d 9/B01.jpg", description: "Living area with open layout and premium material selections." },
  { id: 65, title: "Courtyard Design", category: "residential", image: "/Website/Interior/3d 9/Cortiyard.jpg", description: "Elegant courtyard design with landscaping and natural light integration." },
  { id: 66, title: "Dining Space 2", category: "residential", image: "/Website/Interior/3d 9/Daining 02.jpg", description: "Dining space with refined table setting and ambient lighting." },
  { id: 67, title: "Dining Area Design", category: "residential", image: "/Website/Interior/3d 9/Daining.jpg", description: "Stylish dining area with statement pendant lights and custom furniture." },
  { id: 68, title: "Drawing Room 1", category: "residential", image: "/Website/Interior/3d 9/DRG 01.jpg", description: "Drawing room with classic elegance and modern comfort." },
  { id: 69, title: "Drawing Room 2", category: "residential", image: "/Website/Interior/3d 9/DRG 02.jpg", description: "Drawing room featuring warm textures and curated artwork." },
  { id: 70, title: "Grand Living Room 3", category: "residential", image: "/Website/Interior/HD 3d/HD 2/No WM/Big Livingroom view 3.png", description: "Grand living room with panoramic views and luxurious furnishings." },
  { id: 71, title: "Compact Living Space 2", category: "residential", image: "/Website/Interior/HD 3d/HD 2/No WM/Small Livingroom view 2.png", description: "Compact living space with smart storage and efficient layout." },
  { id: 72, title: "HD Interior Render 1", category: "residential", image: "/Website/Interior/HD 3d/HD 3/20.png", description: "High-definition interior render with photorealistic detail." },
  { id: 73, title: "HD Interior Render 2", category: "residential", image: "/Website/Interior/HD 3d/HD 3/21.png", description: "High-definition interior render showcasing premium finishes." },
  { id: 74, title: "HD Interior Render 3", category: "residential", image: "/Website/Interior/HD 3d/HD 3/22.png", description: "High-definition interior render with layered lighting and texture." },
  { id: 75, title: "HD Interior Render 4", category: "residential", image: "/Website/Interior/HD 3d/HD 3/23.png", description: "High-definition interior render with curated furniture and decor." },
  { id: 76, title: "HD Interior Render 5", category: "residential", image: "/Website/Interior/HD 3d/HD 3/24.png", description: "High-definition interior render with elegant material palette." },
  { id: 77, title: "HD Interior Render 6", category: "residential", image: "/Website/Interior/HD 3d/HD 3/25.png", description: "High-definition interior render with sophisticated design elements." },
  { id: 78, title: "HD Interior Render 7", category: "residential", image: "/Website/Interior/HD 3d/HD 3/26.png", description: "High-definition interior render with warm ambient lighting." },
  { id: 79, title: "HD Interior Render 8", category: "residential", image: "/Website/Interior/HD 3d/HD 3/27.png", description: "High-definition interior render with open layout and natural light." },
  { id: 80, title: "HD Interior Render 9", category: "residential", image: "/Website/Interior/HD 3d/HD 3/28.png", description: "High-definition interior render featuring bespoke joinery." },
  { id: 81, title: "HD Interior Render 10", category: "residential", image: "/Website/Interior/HD 3d/HD 3/29.png", description: "High-definition interior render with refined contemporary styling." },
  { id: 82, title: "HD Interior Render 11", category: "residential", image: "/Website/Interior/HD 3d/HD 3/30.png", description: "High-definition interior render with statement ceiling design." },
  { id: 83, title: "HD Interior Render 12", category: "residential", image: "/Website/Interior/HD 3d/HD 3/31.png", description: "High-definition interior render with premium upholstery and finishes." },
  { id: 84, title: "HD Interior Render 13", category: "residential", image: "/Website/Interior/HD 3d/HD 3/32.png", description: "High-definition interior render with tailored spatial composition." },
  { id: 85, title: "HD Interior Render 14", category: "residential", image: "/Website/Interior/HD 3d/HD 3/33.png", description: "High-definition interior render with luxurious material choices." },
  { id: 86, title: "Themed Bedroom Design", category: "residential", image: "/Website/Interior/Theme/Batman 1.jpg", description: "Custom themed bedroom with immersive design for young enthusiasts." },
  { id: 87, title: "Custom Theme Room", category: "residential", image: "/Website/Interior/Theme/Batman 2.jpg", description: "Creatively themed room with attention to every design detail." },
  { id: 88, title: "Living Room Design A1", category: "residential", image: "/Website/Interior/WM 3d 10/Living room View 01.jpg", description: "Modern living room with balanced proportions and warm palette." },
  { id: 89, title: "Living Room Design A2", category: "residential", image: "/Website/Interior/WM 3d 10/Living room View 02.jpg", description: "Living room with open layout and curated furniture selections." },
  { id: 90, title: "Living Room Design A3", category: "residential", image: "/Website/Interior/WM 3d 10/Living room View 03.jpg", description: "Elegant living room with accent lighting and premium upholstery." },
  { id: 91, title: "Living Room Design B1", category: "residential", image: "/Website/Interior/WM 3d 10/Living room view 1.jpg", description: "Living room with sophisticated color scheme and designer furniture." },
  { id: 92, title: "Living Room Design B2", category: "residential", image: "/Website/Interior/WM 3d 10/Living room view 2.jpg", description: "Living room with layered textures and statement wall design." },
  { id: 93, title: "Living Room Design B3", category: "residential", image: "/Website/Interior/WM 3d 10/Living room view 3.jpg", description: "Living room featuring natural materials and refined aesthetic." },
  { id: 94, title: "Living Room Design B4", category: "residential", image: "/Website/Interior/WM 3d 10/Living room view 4.jpg", description: "Living room with seamless indoor-outdoor connection and premium finishes." },
  { id: 95, title: "Living Room Design C1", category: "residential", image: "/Website/Interior/WM 3d 10/Living room_view_01.jpg", description: "Living room design with cohesive material palette and ambient lighting." },
  { id: 96, title: "Living Room Design C2", category: "residential", image: "/Website/Interior/WM 3d 10/Living room_view_02.jpg", description: "Living room design with bespoke shelving and elegant proportions." },
  { id: 97, title: "Contemporary Living 1", category: "residential", image: "/Website/Interior/WM 3d 11/living view 1.jpg", description: "Contemporary living space with clean lines and premium detailing." },
  { id: 98, title: "Contemporary Living 2", category: "residential", image: "/Website/Interior/WM 3d 11/living view 2.jpg", description: "Contemporary living area with open layout and warm lighting." },
  { id: 99, title: "Contemporary Living 3", category: "residential", image: "/Website/Interior/WM 3d 11/living view 3.jpg", description: "Contemporary living with curated decor and cohesive color story." },
  { id: 100, title: "Main Entrance Design", category: "residential", image: "/Website/Interior/WM 3d 11/Main entrance.jpg", description: "Grand main entrance with statement flooring and welcoming design." },
  { id: 101, title: "Dining Area", category: "residential", image: "/Website/Interior/WM 3d 3/Dining area 1.jpg", description: "Dining area with warm ambiance and refined table setting." },
  { id: 102, title: "Dining Area View 1", category: "residential", image: "/Website/Interior/WM 3d 3/Dining area view 1.jpg", description: "Dining area with statement pendant lighting and custom furniture." },
  { id: 103, title: "Dining Area View 2", category: "residential", image: "/Website/Interior/WM 3d 3/Dining area view 2.jpg", description: "Dining area with elegant decor and harmonious material palette." },
  { id: 104, title: "Drawing Room A1", category: "residential", image: "/Website/Interior/WM 3d 3/Drawing room view 1.jpg", description: "Drawing room with sophisticated layout and premium furniture." },
  { id: 105, title: "Drawing Room A2", category: "residential", image: "/Website/Interior/WM 3d 3/Drawing room view 2.jpg", description: "Drawing room with accent wall and curated artwork display." },
  { id: 106, title: "Drawing Room A3", category: "residential", image: "/Website/Interior/WM 3d 3/Drawing room view 3.jpg", description: "Drawing room with layered lighting and elegant proportions." },
  { id: 107, title: "Drawing Room B2", category: "residential", image: "/Website/Interior/WM 3d 3/Drawing view 2.jpg", description: "Drawing room with refined furnishings and warm color palette." },
  { id: 108, title: "Drawing Room B3", category: "residential", image: "/Website/Interior/WM 3d 3/Drawing view 3.jpg", description: "Drawing room with statement sofa and decorative ceiling design." },
  { id: 109, title: "Drawing Room B4", category: "residential", image: "/Website/Interior/WM 3d 3/Drawing view 4 op.2 (1).jpg", description: "Drawing room with premium upholstery and bespoke joinery." },
  { id: 110, title: "Guest Area Design 1", category: "residential", image: "/Website/Interior/WM 3d 6/Guest area view 1.jpg", description: "Guest area with comfortable seating and welcoming aesthetic." },
  { id: 111, title: "Guest Area Design 2", category: "residential", image: "/Website/Interior/WM 3d 6/Guest area view 2.jpg", description: "Guest area with elegant furnishings and curated accessories." },
  { id: 112, title: "Guest Area Design 3", category: "residential", image: "/Website/Interior/WM 3d 6/Guest area view 3.jpg", description: "Guest area with refined layout and premium material finishes." },
  { id: 113, title: "Home Theatre Design", category: "residential", image: "/Website/Interior/WM 3d 6/home theatre_ view 01.jpg", description: "Dedicated home theatre with acoustic design and immersive lighting." },
  { id: 114, title: "Interior Design Project", category: "residential", image: "/Website/Interior/WM 3d 7/IMG_1401.jpg", description: "Residential interior project with sophisticated design and quality finishes." },
  { id: 115, title: "Interior Render", category: "residential", image: "/Website/Interior/WM 3d 7/IMG_1402.jpg", description: "Detailed interior render with premium material selections." },
  { id: 116, title: "Living Space Design", category: "residential", image: "/Website/Interior/WM 3d 7/IMG_1827.jpg", description: "Living space design with harmonious proportions and warm palette." },
  { id: 117, title: "Residential Render", category: "residential", image: "/Website/Interior/WM 3d 7/IMG_1828.jpg", description: "Residential render showcasing elegant design and photorealistic detail." },
  { id: 118, title: "Interior Project 1", category: "residential", image: "/Website/Interior/WM 3d 7/IMG_2033.jpg", description: "Residential interior project with curated furnishings and modern aesthetic." },
  { id: 119, title: "Interior Project 2", category: "residential", image: "/Website/Interior/WM 3d 7/IMG_2034.jpg", description: "Residential interior project with layered textures and accent lighting." },
  { id: 120, title: "Interior Project 3", category: "residential", image: "/Website/Interior/WM 3d 7/IMG_2035.jpg", description: "Residential interior project with refined color scheme and bespoke details." },
  { id: 121, title: "Interior Design A", category: "residential", image: "/Website/Interior/WM 3d 7/IMG_8688.jpg", description: "Residential interior design with premium finishes and elegant styling." },
  { id: 122, title: "Interior Design B", category: "residential", image: "/Website/Interior/WM 3d 7/IMG_8689.jpg", description: "Residential interior design featuring contemporary furniture and warm tones." },
  { id: 123, title: "Interior Design C", category: "residential", image: "/Website/Interior/WM 3d 7/IMG_8690.jpg", description: "Residential interior design with sophisticated material palette and clean lines." },
  { id: 124, title: "Residential Space 1", category: "residential", image: "/Website/Interior/WM 3d 8/IMG_8952.jpg", description: "Residential space with thoughtful layout and premium material choices." },
  { id: 125, title: "Residential Space 2", category: "residential", image: "/Website/Interior/WM 3d 8/IMG_8953.jpg", description: "Residential space with curated decor and cohesive design language." },
  { id: 126, title: "Residential Space 3", category: "residential", image: "/Website/Interior/WM 3d 8/IMG_8954.jpg", description: "Residential space with elegant proportions and layered lighting." },
  { id: 127, title: "Residential Space 4", category: "residential", image: "/Website/Interior/WM 3d 8/IMG_8956.jpg", description: "Residential space featuring warm ambiance and quality craftsmanship." },
  { id: 128, title: "Home Interior A", category: "residential", image: "/Website/Interior/WM 3d 8/IMG_9237.jpg", description: "Home interior with refined furnishings and sophisticated styling." },
  { id: 129, title: "Home Interior B", category: "residential", image: "/Website/Interior/WM 3d 8/IMG_9238.jpg", description: "Home interior with modern aesthetic and premium material finishes." },
  { id: 130, title: "Home Interior C", category: "residential", image: "/Website/Interior/WM 3d 8/IMG_9239.jpg", description: "Home interior with clean design language and curated accessories." },
  { id: 131, title: "Home Design 1", category: "residential", image: "/Website/Interior/WM 3d 8/IMG_9387.jpg", description: "Home design with elegant layout and high-quality interior finishes." },
  { id: 132, title: "Home Design 2", category: "residential", image: "/Website/Interior/WM 3d 8/IMG_9388.jpg", description: "Home design featuring warm tones and bespoke furniture selections." },
  { id: 133, title: "Home Design 3", category: "residential", image: "/Website/Interior/WM 3d 8/IMG_9389.jpg", description: "Home design with refined proportions and layered material textures." },
  { id: 134, title: "Home Design 4", category: "residential", image: "/Website/Interior/WM 3d 8/IMG_9390.jpg", description: "Home design with sophisticated styling and premium joinery details." },

  // Bedroom (additional)
  { id: 135, title: "Daughter's Bedroom 2", category: "bedroom", image: "/Website/Interior/3d 3/Daughter room_V2.jpg", description: "Elegant bedroom with feminine palette and custom wardrobe." },
  { id: 136, title: "Master Bedroom Suite 2", category: "bedroom", image: "/Website/Interior/3d 3/Master room_V2.jpg", description: "Master bedroom suite with luxurious finishes and statement headboard." },
  { id: 137, title: "Daughter's Room View 1", category: "bedroom", image: "/Website/Interior/3d 4/Daughter room View 01.jpg", description: "Daughter's room with cheerful palette and functional layout." },
  { id: 138, title: "Daughter's Room View 2", category: "bedroom", image: "/Website/Interior/3d 4/Daughter room View 02.jpg", description: "Daughter's room with custom study area and wardrobe design." },
  { id: 139, title: "Premium Bedroom 2", category: "bedroom", image: "/Website/Interior/3d 4/Master room view 02.jpg", description: "Premium bedroom with layered lighting and bespoke headboard." },
  { id: 140, title: "Premium Bedroom 3", category: "bedroom", image: "/Website/Interior/3d 4/Master room view 03.jpg", description: "Premium bedroom with elegant draping and luxury material palette." },
  { id: 141, title: "Bedroom Design A", category: "bedroom", image: "/Website/Interior/3d 8/1.jpg", description: "Bedroom design with contemporary styling and quality finishes." },
  { id: 142, title: "Bedroom Design B", category: "bedroom", image: "/Website/Interior/3d 8/2.jpg", description: "Bedroom design with warm palette and thoughtful space planning." },
  { id: 143, title: "Master Bedroom A1", category: "bedroom", image: "/Website/Interior/3d 8/2kiritbhai m,bed view 1 op.2 (1).jpg", description: "Master bedroom with premium wardrobe and elegant headboard wall." },
  { id: 144, title: "Master Bedroom A2", category: "bedroom", image: "/Website/Interior/3d 8/2kiritbhai m,bed view 1 op.2 (4).jpg", description: "Master bedroom with luxurious finishes and ambient lighting." },
  { id: 145, title: "Ground Floor Bedroom 1", category: "bedroom", image: "/Website/Interior/3d 8/Bayad Revised Ground floor back side Bed room_view_01.jpg", description: "Ground floor bedroom with elegant layout and premium detailing." },
  { id: 146, title: "Ground Floor Bedroom 2", category: "bedroom", image: "/Website/Interior/3d 8/Bayad Revised Ground floor back side Bed room_view_02.jpg", description: "Ground floor bedroom with curated decor and quality finishes." },
  { id: 147, title: "Bedroom Suite View 2", category: "bedroom", image: "/Website/Interior/3d 8/Bed 1 view 2.jpg", description: "Bedroom suite with refined styling and layered ambient lighting." },
  { id: 148, title: "Second Bedroom 1", category: "bedroom", image: "/Website/Interior/3d 8/Bed 2 view 1.jpg", description: "Second bedroom with functional layout and contemporary finishes." },
  { id: 149, title: "Second Bedroom 2", category: "bedroom", image: "/Website/Interior/3d 8/Bed 2 view 2.jpg", description: "Second bedroom with warm tones and bespoke wardrobe design." },
  { id: 150, title: "Third Bedroom 1", category: "bedroom", image: "/Website/Interior/3d 8/Bed 3 view 1.jpg", description: "Third bedroom with clean design and efficient use of space." },
  { id: 151, title: "Third Bedroom 2", category: "bedroom", image: "/Website/Interior/3d 8/Bed 3 view 2.jpg", description: "Third bedroom with accent wall and premium material selections." },
  { id: 152, title: "Bedroom 3 Design 1", category: "bedroom", image: "/Website/Interior/3d 8/BED ROOM 3 VIEW 1.jpg", description: "Bedroom design with elegant proportions and curated accessories." },
  { id: 153, title: "Bedroom 3 Design 2", category: "bedroom", image: "/Website/Interior/3d 8/BED ROOM 3 VIEW 2.jpg", description: "Bedroom design with warm palette and statement lighting fixture." },
  { id: 154, title: "Bedroom Render A", category: "bedroom", image: "/Website/Interior/3d 8/IMG_5714.jpg", description: "Bedroom render with photorealistic detail and premium finishes." },
  { id: 155, title: "Bedroom Render B", category: "bedroom", image: "/Website/Interior/3d 8/IMG_5715.jpg", description: "Bedroom render featuring elegant furniture and layered lighting." },
  { id: 156, title: "Bedroom Render C", category: "bedroom", image: "/Website/Interior/3d 8/IMG_5716.jpg", description: "Bedroom render with sophisticated material palette and clean lines." },
  { id: 157, title: "Bedroom Render D", category: "bedroom", image: "/Website/Interior/3d 8/IMG_5718.jpg", description: "Bedroom render with curated decor and warm ambient atmosphere." },
  { id: 158, title: "Bedroom 232 View 1", category: "bedroom", image: "/Website/Interior/3d 9/232 bed room view 1.jpg", description: "Bedroom with refined layout and contemporary styling." },
  { id: 159, title: "Bedroom 232 View 2", category: "bedroom", image: "/Website/Interior/3d 9/232 bed room view 2.jpg", description: "Bedroom with premium finishes and elegant wardrobe design." },
  { id: 160, title: "Master Suite A", category: "bedroom", image: "/Website/Interior/3d 9/241 kiritbhai m,bed view 1 op.2.jpg", description: "Master suite with luxurious detailing and statement headboard." },
  { id: 161, title: "Master Suite B", category: "bedroom", image: "/Website/Interior/3d 9/241 kiritbhai m,bed view 1.jpg", description: "Master suite with bespoke wardrobe and layered ambient lighting." },
  { id: 162, title: "Master Suite C", category: "bedroom", image: "/Website/Interior/3d 9/241 kiritbhai m,bed view 2(1).jpg", description: "Master suite with elegant proportions and premium material palette." },
  { id: 163, title: "Bedroom 01 A", category: "bedroom", image: "/Website/Interior/3d 9/Bed01 A.jpg", description: "Bedroom with contemporary design and quality interior finishes." },
  { id: 164, title: "Bedroom 01 B", category: "bedroom", image: "/Website/Interior/3d 9/Bed01 B.jpg", description: "Bedroom with warm tones and thoughtfully curated furnishings." },
  { id: 165, title: "Bedroom 02 A", category: "bedroom", image: "/Website/Interior/3d 9/Bed02 A.jpg", description: "Bedroom with refined styling and functional storage solutions." },
  { id: 166, title: "Parents Bedroom 1", category: "bedroom", image: "/Website/Interior/WM 3d 11/Parents bed view 1.jpg", description: "Parents bedroom with serene palette and premium upholstery." },
  { id: 167, title: "Parents Bedroom 2", category: "bedroom", image: "/Website/Interior/WM 3d 11/Parents bed view 2.jpg", description: "Parents bedroom with elegant proportions and bespoke joinery." },
  { id: 168, title: "Reading Room 1", category: "bedroom", image: "/Website/Interior/WM 3d 11/Reading room view 1.jpg", description: "Reading room with curated shelving and warm ambient lighting." },
  { id: 169, title: "Reading Room 2", category: "bedroom", image: "/Website/Interior/WM 3d 11/Reading room view 2.jpg", description: "Reading room with comfortable seating and functional study design." },
  { id: 170, title: "Suite Room 1", category: "bedroom", image: "/Website/Interior/WM 3d 11/Suit room view 1.jpg", description: "Suite room with luxury finishes and sophisticated design language." },
  { id: 171, title: "Suite Room 2", category: "bedroom", image: "/Website/Interior/WM 3d 11/Suit room view 2.jpg", description: "Suite room with premium wardrobe and refined material selections." },
  { id: 172, title: "Bedroom C View 1", category: "bedroom", image: "/Website/Interior/WM 3d 2/Bed 3 view 1.jpg", description: "Bedroom with clean design and quality premium finishes." },
  { id: 173, title: "Bedroom C View 2", category: "bedroom", image: "/Website/Interior/WM 3d 2/Bed 3 view 2.jpg", description: "Bedroom with accent wall and elegant furniture placement." },
  { id: 174, title: "Bedroom D View 1", category: "bedroom", image: "/Website/Interior/WM 3d 2/BED ROOM 3 VIEW 1.jpg", description: "Bedroom with sophisticated styling and curated accessories." },
  { id: 175, title: "Bedroom D View 2", category: "bedroom", image: "/Website/Interior/WM 3d 2/BED ROOM 3 VIEW 2.jpg", description: "Bedroom with layered lighting and premium upholstery." },
  { id: 176, title: "Bedroom E View A", category: "bedroom", image: "/Website/Interior/WM 3d 2/Bed01 A.jpg", description: "Bedroom with harmonious color palette and refined detailing." },
  { id: 177, title: "Bedroom E View B", category: "bedroom", image: "/Website/Interior/WM 3d 2/Bed01 B.jpg", description: "Bedroom with elegant proportions and bespoke wardrobe design." },
  { id: 178, title: "Bedroom F View A", category: "bedroom", image: "/Website/Interior/WM 3d 2/Bed02 A.jpg", description: "Bedroom with modern aesthetic and quality material finishes." },
  { id: 179, title: "Bedroom F View B", category: "bedroom", image: "/Website/Interior/WM 3d 2/Bed02 B.jpg", description: "Bedroom with warm tones and thoughtful spatial composition." },
  { id: 180, title: "Bedroom 1 View 1", category: "bedroom", image: "/Website/Interior/WM 3d 2/Bedroom 1 view 1.jpg", description: "Bedroom with premium finishes and contemporary styling." },
  { id: 181, title: "Bedroom 1 View 2", category: "bedroom", image: "/Website/Interior/WM 3d 2/Bedroom 1 view 2.jpg", description: "Bedroom with curated decor and layered ambient lighting." },
  { id: 182, title: "Bedroom 2 View 1", category: "bedroom", image: "/Website/Interior/WM 3d 3/Bedroom 2 view 1.jpg", description: "Bedroom with elegant layout and high-quality interior finishes." },
  { id: 183, title: "Bedroom 2 View 2", category: "bedroom", image: "/Website/Interior/WM 3d 3/Bedroom 2 view 2.jpg", description: "Bedroom with warm palette and bespoke furniture selections." },
  { id: 184, title: "First Floor Bedroom 2A", category: "bedroom", image: "/Website/Interior/WM 3d 4/F.F_BEdroom 2_1.jpg", description: "First floor bedroom with refined design and premium finishes." },
  { id: 185, title: "First Floor Bedroom 2B", category: "bedroom", image: "/Website/Interior/WM 3d 4/F.F_Bedroom_2_2.jpg", description: "First floor bedroom with elegant proportions and custom wardrobe." },
  { id: 186, title: "First Floor Bedroom 3A", category: "bedroom", image: "/Website/Interior/WM 3d 4/F.F_Bedroom_3_01.jpg", description: "First floor bedroom with contemporary styling and quality materials." },
  { id: 187, title: "First Floor Bedroom 3B", category: "bedroom", image: "/Website/Interior/WM 3d 4/F.F_Bedroom_3_view_02.jpg", description: "First floor bedroom with warm tones and sophisticated detailing." },
  { id: 188, title: "First Floor Lounge", category: "bedroom", image: "/Website/Interior/WM 3d 4/F.Floor_Lounge_view_01 .jpg", description: "First floor lounge with comfortable seating and elegant layout." },
  { id: 189, title: "Family Dining View 1", category: "bedroom", image: "/Website/Interior/WM 3d 4/Family seating Dining_view_01.jpg", description: "Family dining area with warm ambiance and quality furnishings." },
  { id: 190, title: "Family Dining View 2", category: "bedroom", image: "/Website/Interior/WM 3d 4/Family seating Dining_view_02.jpg", description: "Family dining with elegant table setting and ambient lighting." },
  { id: 191, title: "Family Dining View 3", category: "bedroom", image: "/Website/Interior/WM 3d 4/Family seating Dining_view_03.jpg", description: "Family dining space with refined decor and cohesive design." },
  { id: 192, title: "Front Bedroom View 1", category: "bedroom", image: "/Website/Interior/WM 3d 4/FIRST FLOOR FRONT RIGHT SIDE BEDROOM_view_01.jpg", description: "Front bedroom with premium finishes and contemporary design." },
  { id: 193, title: "Front Bedroom View 2", category: "bedroom", image: "/Website/Interior/WM 3d 4/FIRST FLOOR FRONT RIGHT SIDE BEDROOM_view_02.jpg", description: "Front bedroom with elegant proportions and bespoke details." },
  { id: 194, title: "Front Bedroom View 3", category: "bedroom", image: "/Website/Interior/WM 3d 4/FIRST FLOOR FRONT RIGHT SIDE BEDROOM_view_03.jpg", description: "Front bedroom with layered lighting and curated furnishings." },
  { id: 195, title: "Left Back Bedroom 1", category: "bedroom", image: "/Website/Interior/WM 3d 5/First Floor left  back side bedroom_view_1.jpg", description: "Bedroom with refined layout and high-quality material finishes." },
  { id: 196, title: "Left Back Bedroom 2", category: "bedroom", image: "/Website/Interior/WM 3d 5/First Floor left  back side bedroom_view_2.jpg", description: "Bedroom with warm palette and thoughtfully designed storage." },
  { id: 197, title: "Left Back Bedroom 3", category: "bedroom", image: "/Website/Interior/WM 3d 5/First Floor left  back side bedroom_view_3.jpg", description: "Bedroom with clean aesthetic and premium upholstery selections." },
  { id: 198, title: "Right Back Bedroom 1", category: "bedroom", image: "/Website/Interior/WM 3d 5/First Floor right back side bedroom_view_01.jpg", description: "Bedroom with elegant styling and quality interior finishes." },
  { id: 199, title: "Right Back Bedroom 2", category: "bedroom", image: "/Website/Interior/WM 3d 5/First Floor right back side bedroom_view_02.jpg", description: "Bedroom with sophisticated layout and curated decor." },
  { id: 200, title: "Right Back Bedroom 3", category: "bedroom", image: "/Website/Interior/WM 3d 5/First Floor right back side bedroom_view_03.jpg", description: "Bedroom with layered lighting and premium material palette." },
  { id: 201, title: "Floor Bedroom View 1", category: "bedroom", image: "/Website/Interior/WM 3d 5/floor bed view 1.jpg", description: "Bedroom with contemporary design and quality craftsmanship." },
  { id: 202, title: "Floor Bedroom View 2", category: "bedroom", image: "/Website/Interior/WM 3d 5/floor bed view 2.jpg", description: "Bedroom with warm tones and refined spatial composition." },
  { id: 203, title: "Floor Bedroom View 3", category: "bedroom", image: "/Website/Interior/WM 3d 5/floor bed view 3.jpg", description: "Bedroom with curated furnishings and ambient lighting design." },
  { id: 204, title: "Grandmother Bedroom 1", category: "bedroom", image: "/Website/Interior/WM 3d 5/Grand mother Badroom View 01.jpg", description: "Comfortable bedroom with serene palette and accessible design." },
  { id: 205, title: "Grandmother Bedroom 2", category: "bedroom", image: "/Website/Interior/WM 3d 5/Grand mother Badroom View 02.jpg", description: "Bedroom with warm finishes and thoughtful ergonomic layout." },
  { id: 206, title: "Ground Floor Bedroom A", category: "bedroom", image: "/Website/Interior/WM 3d 6/Grand mother bedroom,Ground floor_view_01.jpg", description: "Ground floor bedroom with serene design and premium finishes." },
  { id: 207, title: "Ground Floor Bedroom B", category: "bedroom", image: "/Website/Interior/WM 3d 6/Grand mother bedroom,Ground floor_view_02.jpg", description: "Ground floor bedroom with elegant layout and warm color palette." },
  { id: 208, title: "Ground Floor Bed 1A", category: "bedroom", image: "/Website/Interior/WM 3d 6/Ground floor Bed 1_01.jpg", description: "Ground floor bedroom with contemporary styling and quality materials." },
  { id: 209, title: "Ground Floor Bed 1B", category: "bedroom", image: "/Website/Interior/WM 3d 6/Ground floor Bed 1_02.jpg", description: "Ground floor bedroom with curated decor and layered lighting." },
  { id: 210, title: "Bedroom Render E", category: "bedroom", image: "/Website/Interior/WM 3d 6/IMG_0428.jpg", description: "Bedroom render with photorealistic detail and elegant styling." },
  { id: 211, title: "Bedroom Render F", category: "bedroom", image: "/Website/Interior/WM 3d 6/IMG_0429.jpg", description: "Bedroom render featuring warm palette and bespoke furniture." },
  { id: 212, title: "Bedroom Render G", category: "bedroom", image: "/Website/Interior/WM 3d 6/IMG_1061.jpg", description: "Bedroom render with premium finishes and refined proportions." },
  { id: 213, title: "Bedroom Render H", category: "bedroom", image: "/Website/Interior/WM 3d 7/IMG_1062.jpg", description: "Bedroom render with sophisticated design and quality materials." },
  { id: 214, title: "Bedroom Render I", category: "bedroom", image: "/Website/Interior/WM 3d 7/IMG_1063.jpg", description: "Bedroom render with curated accessories and ambient lighting." },
  { id: 215, title: "Kids Bedroom View 2", category: "bedroom", image: "/Website/Interior/WM 3d 9/Kids bedroom View 2.jpg", description: "Kids bedroom with playful design and functional storage solutions." },
  { id: 216, title: "Kids Room View 1", category: "bedroom", image: "/Website/Interior/WM 3d 9/Kids room view 01.jpg", description: "Kids room with vibrant palette and creative design elements." },
  { id: 217, title: "Kids Room View 2", category: "bedroom", image: "/Website/Interior/WM 3d 9/Kids room view 02.jpg", description: "Kids room with fun themes and smart space utilization." },
  { id: 218, title: "Kids Room View 3", category: "bedroom", image: "/Website/Interior/WM 3d 9/Kids room view 03.jpg", description: "Kids room with engaging design and durable quality finishes." },
  { id: 219, title: "Bedroom Design 1A", category: "bedroom", image: "/Website/Interior/wm 3d 1/1.jpg", description: "Bedroom design with contemporary styling and premium finishes." },
  { id: 220, title: "Bedroom Design 1B", category: "bedroom", image: "/Website/Interior/wm 3d 1/2.jpg", description: "Bedroom design with warm palette and elegant furniture." },
  { id: 221, title: "Master Bedroom WM1", category: "bedroom", image: "/Website/Interior/wm 3d 1/2kiritbhai m,bed view 1 op.2 (1).jpg", description: "Master bedroom with luxurious finishes and statement headboard wall." },
  { id: 222, title: "Master Bedroom WM2", category: "bedroom", image: "/Website/Interior/wm 3d 1/2kiritbhai m,bed view 1 op.2 (2)(1).jpg", description: "Master bedroom with bespoke wardrobe and ambient lighting design." },
  { id: 223, title: "Ground Floor Bed WM1", category: "bedroom", image: "/Website/Interior/wm 3d 1/Bayad Revised Ground floor back side Bed room_view_01.jpg", description: "Ground floor bedroom with elegant layout and quality finishes." },
  { id: 224, title: "Ground Floor Bed WM2", category: "bedroom", image: "/Website/Interior/wm 3d 1/Bayad Revised Ground floor back side Bed room_view_02.jpg", description: "Ground floor bedroom with refined decor and premium material palette." },
  { id: 225, title: "Bedroom WM View 1", category: "bedroom", image: "/Website/Interior/wm 3d 1/Bed 1 view 1.jpg", description: "Bedroom with contemporary design and layered ambient lighting." },
  { id: 226, title: "Bedroom WM View 2", category: "bedroom", image: "/Website/Interior/wm 3d 1/Bed 1 view 2.jpg", description: "Bedroom with warm tones and bespoke furniture selections." },
  { id: 227, title: "Second Bed WM 1", category: "bedroom", image: "/Website/Interior/wm 3d 1/Bed 2 view 1.jpg", description: "Second bedroom with functional layout and premium finishes." },
  { id: 228, title: "Second Bed WM 2", category: "bedroom", image: "/Website/Interior/wm 3d 1/Bed 2 view 2.jpg", description: "Second bedroom with refined styling and quality craftsmanship." },

  // Kitchen (additional)
  { id: 229, title: "Modular Kitchen 2", category: "kitchen", image: "/Website/Interior/3d 4/Kitchen view 2.jpg", description: "Modular kitchen with smart storage and premium appliances." },
  { id: 230, title: "Premium Kitchen 2", category: "kitchen", image: "/Website/Interior/HD 3d/HD 2/No WM/Kitchen view 2.png", description: "Premium kitchen with high-end cabinetry and elegant countertops." },
  { id: 231, title: "Kitchen Design A", category: "kitchen", image: "/Website/Interior/WM 3d 9/Kichen view 01.jpg", description: "Kitchen design with modern layout and quality material finishes." },
  { id: 232, title: "Kitchen Design B", category: "kitchen", image: "/Website/Interior/WM 3d 9/Kichen view 02.jpg", description: "Kitchen design with integrated appliances and clean lines." },
  { id: 233, title: "Kitchen View 1", category: "kitchen", image: "/Website/Interior/WM 3d 9/Kitchen view 01.jpg", description: "Kitchen with efficient workflow design and premium cabinetry." },

  // Bathroom (additional)
  { id: 234, title: "Master Bathroom 3", category: "bathroom", image: "/Website/Interior/Bathroom 3d/New WM Bathroom/master bathroom v3.jpg", description: "Master bathroom with spa-inspired design and premium fixtures." },
  { id: 235, title: "Parents Bathroom 2", category: "bathroom", image: "/Website/Interior/Bathroom 3d/New WM Bathroom/parents bathroom v2.jpg", description: "Parents bathroom with elegant marble finishes and modern fittings." },
  { id: 236, title: "Modern Bathroom 2", category: "bathroom", image: "/Website/Interior/Bathroom 3d/New WM Bathroom/son bathroom v2.jpg", description: "Modern bathroom with clean lines and contemporary fixtures." },
  { id: 237, title: "Modern Bathroom 3", category: "bathroom", image: "/Website/Interior/Bathroom 3d/New WM Bathroom/son bathroom v3.jpg", description: "Modern bathroom with smart layout and quality material finishes." },
  { id: 238, title: "Bathroom Design 1", category: "bathroom", image: "/Website/Interior/Bathroom 3d/WM Bathroom/3d Bathroom (1).jpg", description: "Bathroom design with refined aesthetic and premium fixtures." },
  { id: 239, title: "Bathroom Design 2", category: "bathroom", image: "/Website/Interior/Bathroom 3d/WM Bathroom/3d Bathroom (24).jpg", description: "Bathroom design with elegant tilework and modern fittings." },
  { id: 240, title: "Bathroom Design 3", category: "bathroom", image: "/Website/Interior/Bathroom 3d/WM Bathroom/3d Bathroom (26).jpg", description: "Bathroom design with clean lines and sophisticated material palette." },
  { id: 241, title: "Bathroom Design 4", category: "bathroom", image: "/Website/Interior/Bathroom 3d/WM Bathroom/3d Bathroom (27).jpg", description: "Bathroom design with luxury finishes and statement vanity." },
  { id: 242, title: "Bathroom Design 5", category: "bathroom", image: "/Website/Interior/Bathroom 3d/WM Bathroom/3d Bathroom (28).jpg", description: "Bathroom design with contemporary layout and quality fixtures." },
  { id: 243, title: "Bathroom Design 6", category: "bathroom", image: "/Website/Interior/Bathroom 3d/WM Bathroom/3d Bathroom (29).jpg", description: "Bathroom design with elegant proportions and premium fittings." },
  { id: 244, title: "Bathroom Design 7", category: "bathroom", image: "/Website/Interior/Bathroom 3d/WM Bathroom/3d Bathroom (30).jpg", description: "Bathroom design with refined styling and high-end material finishes." },
  { id: 245, title: "Bathroom Design 8", category: "bathroom", image: "/Website/Interior/Bathroom 3d/WM Bathroom/3d Bathroom (31).jpg", description: "Bathroom design with modern aesthetic and spa-like atmosphere." },
  { id: 246, title: "Bathroom Design 9", category: "bathroom", image: "/Website/Interior/Bathroom 3d/WM Bathroom/3d Bathroom (32).jpg", description: "Bathroom design with premium tilework and contemporary fixtures." },
  { id: 247, title: "Bathroom Design 10", category: "bathroom", image: "/Website/Interior/Bathroom 3d/WM Bathroom/3d Bathroom (33).jpg", description: "Bathroom design with luxurious finishes and elegant spatial layout." },
  { id: 248, title: "Bathroom Suite A1", category: "bathroom", image: "/Website/Interior/Bathroom 3d/WM Bathroom/3d Bathroom 001 (1).jpg", description: "Bathroom suite with premium fixtures and refined design." },
  { id: 249, title: "Bathroom Suite A2", category: "bathroom", image: "/Website/Interior/Bathroom 3d/WM Bathroom/3d Bathroom 001 (2).jpg", description: "Bathroom suite with elegant tilework and quality material palette." },
  { id: 250, title: "Bathroom Suite J1", category: "bathroom", image: "/Website/Interior/Bathroom 3d/WM Bathroom/3d Bathroom 0010 (1).jpg", description: "Bathroom suite with contemporary design and luxury finishes." },
  { id: 251, title: "Bathroom Suite J2", category: "bathroom", image: "/Website/Interior/Bathroom 3d/WM Bathroom/3d Bathroom 0010 (2).jpg", description: "Bathroom suite with modern fittings and refined material choices." },
  { id: 252, title: "Bathroom Suite B1", category: "bathroom", image: "/Website/Interior/Bathroom 3d/WM Bathroom/3d Bathroom 002 (1).jpg", description: "Bathroom suite with clean lines and premium fixture selections." },
  { id: 253, title: "Bathroom Suite B2", category: "bathroom", image: "/Website/Interior/Bathroom 3d/WM Bathroom/3d Bathroom 002 (2).jpg", description: "Bathroom suite with sophisticated design and elegant vanity." },
  { id: 254, title: "Bathroom Suite C1", category: "bathroom", image: "/Website/Interior/Bathroom 3d/WM Bathroom/3d Bathroom 003 (1).jpg", description: "Bathroom suite with spa-like atmosphere and quality finishes." },
  { id: 255, title: "Bathroom Suite C2", category: "bathroom", image: "/Website/Interior/Bathroom 3d/WM Bathroom/3d Bathroom 003 (2).jpg", description: "Bathroom suite with premium tilework and contemporary fittings." },
  { id: 256, title: "Bathroom Suite D1", category: "bathroom", image: "/Website/Interior/Bathroom 3d/WM Bathroom/3d Bathroom 004 (1).jpg", description: "Bathroom suite with elegant proportions and luxury material palette." },
  { id: 257, title: "Bathroom Suite D2", category: "bathroom", image: "/Website/Interior/Bathroom 3d/WM Bathroom/3d Bathroom 004 (2).jpg", description: "Bathroom suite with refined styling and high-end fixtures." },
  { id: 258, title: "Bathroom Suite E1", category: "bathroom", image: "/Website/Interior/Bathroom 3d/WM Bathroom/3d Bathroom 005 (1).jpg", description: "Bathroom suite with modern layout and premium material finishes." },
  { id: 259, title: "Bathroom Suite E2", category: "bathroom", image: "/Website/Interior/Bathroom 3d/WM Bathroom/3d Bathroom 005 (2).jpg", description: "Bathroom suite with sophisticated decor and quality fittings." },
  { id: 260, title: "Bathroom Suite F1", category: "bathroom", image: "/Website/Interior/Bathroom 3d/WM Bathroom/3d Bathroom 006 (1).jpg", description: "Bathroom suite with elegant tilework and premium vanity design." },
  { id: 261, title: "Bathroom Suite F2", category: "bathroom", image: "/Website/Interior/Bathroom 3d/WM Bathroom/3d Bathroom 006 (2).jpg", description: "Bathroom suite with contemporary styling and luxury finishes." },
  { id: 262, title: "Bathroom Suite G1", category: "bathroom", image: "/Website/Interior/Bathroom 3d/WM Bathroom/3d Bathroom 007 (1).jpg", description: "Bathroom suite with clean aesthetic and premium fixture selections." },
  { id: 263, title: "Bathroom Suite G2", category: "bathroom", image: "/Website/Interior/Bathroom 3d/WM Bathroom/3d Bathroom 007 (2).jpg", description: "Bathroom suite with refined proportions and high-end fittings." },
  { id: 264, title: "Bathroom Suite H1", category: "bathroom", image: "/Website/Interior/Bathroom 3d/WM Bathroom/3d Bathroom 008 (1).jpg", description: "Bathroom suite with elegant material palette and modern design." },
  { id: 265, title: "Bathroom Suite H2", category: "bathroom", image: "/Website/Interior/Bathroom 3d/WM Bathroom/3d Bathroom 008 (2).jpg", description: "Bathroom suite with premium tilework and sophisticated layout." },
  { id: 266, title: "Bathroom Suite I1", category: "bathroom", image: "/Website/Interior/Bathroom 3d/WM Bathroom/3d Bathroom 009 (1).jpg", description: "Bathroom suite with luxury finishes and spa-inspired design." },
  { id: 267, title: "Bathroom Suite I2", category: "bathroom", image: "/Website/Interior/Bathroom 3d/WM Bathroom/3d Bathroom 009 (2).jpg", description: "Bathroom suite with refined styling and quality fixture choices." },

  // Office (additional)
  { id: 268, title: "Office Design A", category: "office", image: "/Website/Interior/Office 3d/1 (1).jpeg", description: "Professional office design with ergonomic layout and modern aesthetic." },
  { id: 269, title: "Office Design B", category: "office", image: "/Website/Interior/Office 3d/1 (4).jpeg", description: "Office design with collaborative spaces and premium finishes." },
  { id: 270, title: "Office Design C", category: "office", image: "/Website/Interior/Office 3d/1 (5).jpeg", description: "Office design with efficient workflow and contemporary styling." },
  { id: 271, title: "Office Design D", category: "office", image: "/Website/Interior/Office 3d/1 (6).jpeg", description: "Office design with refined material palette and functional layout." },
  { id: 272, title: "Office Space 1A", category: "office", image: "/Website/Interior/Office 3d/office 1 (1).jpeg", description: "Office space with modern design and productivity-focused layout." },
  { id: 273, title: "Office Space 1B", category: "office", image: "/Website/Interior/Office 3d/office 1 (2).jpeg", description: "Office space with open plan and premium material finishes." },
  { id: 274, title: "Office Space 1C", category: "office", image: "/Website/Interior/Office 3d/office 1 (3).jpeg", description: "Office space with ergonomic workstations and quality design." },
  { id: 275, title: "Office Space 1D", category: "office", image: "/Website/Interior/Office 3d/office 1 (4).jpeg", description: "Office space with contemporary styling and efficient space planning." },
  { id: 276, title: "Office Space 1E", category: "office", image: "/Website/Interior/Office 3d/office 1 (5).jpeg", description: "Office space with collaborative areas and refined aesthetic." },
  { id: 277, title: "Office Space 1F", category: "office", image: "/Website/Interior/Office 3d/office 1 (6).jpeg", description: "Office space with premium finishes and professional design." },
  { id: 278, title: "Office Space 2A", category: "office", image: "/Website/Interior/Office 3d/office2 (1).jpeg", description: "Office space with modern layout and sophisticated decor." },
  { id: 279, title: "Office Space 2B", category: "office", image: "/Website/Interior/Office 3d/office2 (2).jpeg", description: "Office space with quality material finishes and functional design." },
  { id: 280, title: "Office Space 2C", category: "office", image: "/Website/Interior/Office 3d/office2 (3).jpeg", description: "Office space with ergonomic layout and contemporary styling." },
  { id: 281, title: "Office Space 2D", category: "office", image: "/Website/Interior/Office 3d/office2 (4).jpeg", description: "Office space with premium fixtures and cohesive design language." },
  { id: 282, title: "Office Space 2E", category: "office", image: "/Website/Interior/Office 3d/office2 (5).jpeg", description: "Office space with refined proportions and professional finishes." },
  { id: 283, title: "Office Space 2F", category: "office", image: "/Website/Interior/Office 3d/office2 (6).jpeg", description: "Office space with modern aesthetic and quality workstation design." },
  { id: 284, title: "Office Space 2G", category: "office", image: "/Website/Interior/Office 3d/office2 (7).jpeg", description: "Office space with collaborative design and premium material palette." },
  { id: 285, title: "Office Space 3A", category: "office", image: "/Website/Interior/Office 3d/office3 (1).jpeg", description: "Office space with sophisticated layout and high-end finishes." },
  { id: 286, title: "Office Space 3B", category: "office", image: "/Website/Interior/Office 3d/office3 (2).jpeg", description: "Office space with contemporary design and efficient space utilization." },
  { id: 287, title: "Office Space 3C", category: "office", image: "/Website/Interior/Office 3d/office3 (3).jpeg", description: "Office space with refined aesthetic and premium material choices." },
  { id: 288, title: "Office Space 3D", category: "office", image: "/Website/Interior/Office 3d/office3 (4).jpeg", description: "Office space with modern workstations and quality design finishes." },
  { id: 289, title: "Office Space 3E", category: "office", image: "/Website/Interior/Office 3d/office3 (5).jpeg", description: "Office space with professional styling and collaborative areas." },
  { id: 290, title: "Open Office 2", category: "office", image: "/Website/Interior/Office 3d 2/IMG_3258.jpg", description: "Open office with ergonomic layout and premium material finishes." },
  { id: 291, title: "Open Office 3", category: "office", image: "/Website/Interior/Office 3d 2/IMG_3259.jpg", description: "Open office with collaborative design and modern aesthetic." },
  { id: 292, title: "Open Office 4", category: "office", image: "/Website/Interior/Office 3d 2/IMG_3260.jpg", description: "Open office with efficient workflow design and quality finishes." },
  { id: 293, title: "Open Office 5", category: "office", image: "/Website/Interior/Office 3d 2/IMG_3261.jpg", description: "Open office with contemporary styling and professional layout." },
  { id: 294, title: "Office Interior A", category: "office", image: "/Website/Interior/Office 3d 2/IMG_5986.jpg", description: "Office interior with sophisticated design and premium material palette." },
  { id: 295, title: "Office Interior B", category: "office", image: "/Website/Interior/Office 3d 2/IMG_5987.jpg", description: "Office interior with refined proportions and high-end finishes." },

  // Commercial (additional)
  { id: 296, title: "Jewellery Showroom 2", category: "commercial", image: "/Website/Interior/Jewellery Showroom/Gujarat Jewellers view 2.jpg", description: "Jewellery showroom with luxury display and premium finishes." },
  { id: 297, title: "Jewellery Showroom 3", category: "commercial", image: "/Website/Interior/Jewellery Showroom/Gujarat Jewellers view 3.jpg", description: "Jewellery showroom with elegant lighting and refined display cases." },
  { id: 298, title: "Jewellery Showroom 4", category: "commercial", image: "/Website/Interior/Jewellery Showroom/Gujarat Jewellers view 4.jpg", description: "Jewellery showroom with sophisticated layout and premium detailing." },
  { id: 299, title: "Rooftop Restaurant 2", category: "commercial", image: "/Website/Interior/Resataurant Rooftop/35.png", description: "Rooftop restaurant with panoramic setting and elegant furniture." },
  { id: 300, title: "Rooftop Restaurant 3", category: "commercial", image: "/Website/Interior/Resataurant Rooftop/36.png", description: "Rooftop restaurant with ambient lighting and stylish outdoor design." },
  { id: 301, title: "Rooftop Restaurant 4", category: "commercial", image: "/Website/Interior/Resataurant Rooftop/37.png", description: "Rooftop restaurant with curated seating and refined outdoor aesthetic." },
  { id: 302, title: "Rooftop Restaurant 5", category: "commercial", image: "/Website/Interior/Resataurant Rooftop/38.png", description: "Rooftop restaurant with statement design and premium outdoor finishes." },
  { id: 303, title: "Restaurant Interior 2", category: "commercial", image: "/Website/Interior/Restaurant 3d/Hocco_View02-1.jpg", description: "Restaurant interior with warm ambiance and sophisticated decor." },
  { id: 304, title: "Restaurant Interior 3", category: "commercial", image: "/Website/Interior/Restaurant 3d/Hocco_View03-2.jpg", description: "Restaurant interior with elegant seating arrangement and lighting." },
  { id: 305, title: "Restaurant Interior 4", category: "commercial", image: "/Website/Interior/Restaurant 3d/Hocco_View04-2.jpg", description: "Restaurant interior with curated aesthetic and premium finishes." },
  { id: 306, title: "Restaurant Interior 5", category: "commercial", image: "/Website/Interior/Restaurant 3d/Hocco_View05-2.jpg", description: "Restaurant interior with statement design and refined material palette." },
  { id: 307, title: "Restaurant Interior 6", category: "commercial", image: "/Website/Interior/Restaurant 3d/Hocco_View06-2.jpg", description: "Restaurant interior with vibrant atmosphere and quality craftsmanship." },
  { id: 308, title: "Salon Design 2", category: "commercial", image: "/Website/Interior/Salon/WM Salon (6).jpg", description: "Salon design with sleek styling stations and modern aesthetic." },
  { id: 309, title: "Salon Design 3", category: "commercial", image: "/Website/Interior/Salon/WM Salon (7).jpg", description: "Salon design with premium fixtures and refined interior detailing." },
  { id: 310, title: "Salon Design 4", category: "commercial", image: "/Website/Interior/Salon/WM Salon (8).jpg", description: "Salon design with elegant layout and high-end material finishes." },
  { id: 311, title: "Salon Design 5", category: "commercial", image: "/Website/Interior/Salon/WM Salon (9).jpg", description: "Salon design with contemporary styling and quality workstation design." },
  { id: 312, title: "Salon Design 6", category: "commercial", image: "/Website/Interior/Salon/WM Salon (10).jpg", description: "Salon design with sophisticated decor and premium fixture selections." },
  { id: 313, title: "Salon Design 7", category: "commercial", image: "/Website/Interior/Salon/WM Salon (11).jpg", description: "Salon design with modern aesthetic and curated interior details." },
  { id: 314, title: "Salon Design 8", category: "commercial", image: "/Website/Interior/Salon/WM Salon (12).jpg", description: "Salon design with refined proportions and premium material palette." },
  { id: 315, title: "Garment Showroom 2", category: "commercial", image: "/Website/Interior/Showroom 3d/234 Garment showroom view 2.jpg", description: "Garment showroom with strategic display and elegant layout." },
  { id: 316, title: "Garment Showroom 3", category: "commercial", image: "/Website/Interior/Showroom 3d/234 Garment showroom view 3.jpg", description: "Garment showroom with curated product presentation and premium finishes." },
  { id: 317, title: "Garment Showroom 4", category: "commercial", image: "/Website/Interior/Showroom 3d/234 Garment showroom view 4.jpg", description: "Garment showroom with sophisticated design and quality interior styling." },
  { id: 318, title: "Garment Showroom 5", category: "commercial", image: "/Website/Interior/Showroom 3d/234 Garment showroom view 5.jpg", description: "Garment showroom with refined layout and premium display solutions." },
  { id: 319, title: "Showroom Interior A", category: "commercial", image: "/Website/Interior/Showroom 3d/IMG_8275.jpg", description: "Showroom interior with elegant display design and quality finishes." },
  { id: 320, title: "Showroom Interior B", category: "commercial", image: "/Website/Interior/Showroom 3d/IMG_8276.jpg", description: "Showroom interior with modern aesthetic and refined material palette." },
  { id: 321, title: "Hospital Consulting Room 1", category: "commercial", image: "/Website/Interior/Hospital/consuting room view 1.jpg", description: "Medical consulting room with functional design and calming aesthetic." },
  { id: 322, title: "Hospital Consulting Room 2", category: "commercial", image: "/Website/Interior/Hospital/consuting room view 2.jpg", description: "Medical consulting room with clean layout and quality finishes." },
  { id: 323, title: "Trauma Center Design 1", category: "commercial", image: "/Website/Interior/Hospital/Trauma center view 1.jpg", description: "Trauma center with efficient layout and clinical precision design." },
  { id: 324, title: "Trauma Center Design 2", category: "commercial", image: "/Website/Interior/Hospital/Trauma center view 2.jpg", description: "Trauma center with functional design and high-quality material finishes." },
  { id: 325, title: "Trauma Center Design 3", category: "commercial", image: "/Website/Interior/Hospital/Trauma center view 3.jpg", description: "Trauma center with optimized workflow and contemporary clinical aesthetic." },
  { id: 326, title: "Hospital Waiting Area 1", category: "commercial", image: "/Website/Interior/Hospital/Waiting area view 1.jpg", description: "Hospital waiting area with calming design and comfortable seating." },
  { id: 327, title: "Hospital Waiting Area 2", category: "commercial", image: "/Website/Interior/Hospital/Waiting area view 2.jpg", description: "Hospital waiting area with warm palette and welcoming atmosphere." },
  { id: 328, title: "Hospital Waiting Area 3", category: "commercial", image: "/Website/Interior/Hospital/Waiting area view 3.jpg", description: "Hospital waiting area with functional layout and quality finishes." },

  // Exterior (additional)
  { id: 329, title: "Exterior Design View 1", category: "exterior", image: "/Website/Exterior/1/Exterior View 1.JPG", description: "Contemporary exterior design with refined facade and quality materials." },
  { id: 330, title: "Exterior Design View 2", category: "exterior", image: "/Website/Exterior/1/Exterior View 2.JPG", description: "Exterior design with elegant proportions and premium finish selections." },
  { id: 331, title: "Exterior Design View 3", category: "exterior", image: "/Website/Exterior/1/Exterior View 3.JPG", description: "Exterior design with modern aesthetic and sophisticated facade detailing." },
  { id: 332, title: "Elevation Design 1", category: "exterior", image: "/Website/Exterior/2/ele view 1.jpg", description: "Building elevation with contemporary design and premium cladding." },
  { id: 333, title: "Elevation Design 2", category: "exterior", image: "/Website/Exterior/2/ele view 2.jpg", description: "Building elevation with refined proportions and elegant facade treatment." },
  { id: 334, title: "Exterior Render", category: "exterior", image: "/Website/Exterior/2/IMG_9874.jpg", description: "Photorealistic exterior render with detailed material and lighting." },
  { id: 335, title: "Exterior Project 1", category: "exterior", image: "/Website/Exterior/4/1 (2).jpg", description: "Exterior project with modern design and quality material selections." },
  { id: 336, title: "Exterior Project 2", category: "exterior", image: "/Website/Exterior/4/1 (3).jpg", description: "Exterior project with refined facade and contemporary styling." },
  { id: 337, title: "Exterior Project 3", category: "exterior", image: "/Website/Exterior/4/1 (4).jpg", description: "Exterior project with elegant proportions and premium finishes." },
  { id: 338, title: "Exterior Project 4", category: "exterior", image: "/Website/Exterior/4/1 (5).jpg", description: "Exterior project with sophisticated design and quality cladding." },
  { id: 339, title: "Exterior Project 5", category: "exterior", image: "/Website/Exterior/4/1 (6).jpg", description: "Exterior project with contemporary aesthetic and refined detailing." },
  { id: 340, title: "Exterior Project 6", category: "exterior", image: "/Website/Exterior/4/1 (7).jpg", description: "Exterior project with modern facade treatment and premium materials." },
  { id: 341, title: "Exterior Project 7", category: "exterior", image: "/Website/Exterior/4/1 (8).jpg", description: "Exterior project with cohesive design language and quality finishes." },
  { id: 342, title: "Exterior Project 8", category: "exterior", image: "/Website/Exterior/4/1 (9).jpg", description: "Exterior project with elegant proportions and contemporary styling." },
  { id: 343, title: "Exterior Project 9", category: "exterior", image: "/Website/Exterior/4/1 (10).jpg", description: "Exterior project with refined material palette and modern aesthetic." },
  { id: 344, title: "Exterior Project 10", category: "exterior", image: "/Website/Exterior/4/1 (11).jpg", description: "Exterior project with sophisticated facade and premium design finishes." },
  { id: 345, title: "Apartment View", category: "exterior", image: "/Website/Exterior/Commercial Building/Apartment view .jpg", description: "Apartment building with modern facade and residential design." },
  { id: 346, title: "Apartment View 2", category: "exterior", image: "/Website/Exterior/Commercial Building/Apartment view 2 .jpg", description: "Apartment building with elegant exterior and quality facade finishes." },
  { id: 347, title: "Corner Night View", category: "exterior", image: "/Website/Exterior/Commercial Building/corner night view.jpg", description: "Commercial building corner view with dramatic night-time illumination." },
  { id: 348, title: "Night Render", category: "exterior", image: "/Website/Exterior/Commercial Building/Night_1.jpg", description: "Photorealistic night render with architectural lighting design." },
  { id: 349, title: "Commercial Building 2B", category: "exterior", image: "/Website/Exterior/Commercial Building 2/2.png", description: "Commercial building with contemporary facade and modern design." },
  { id: 350, title: "Commercial Building 2C", category: "exterior", image: "/Website/Exterior/Commercial Building 2/3.png", description: "Commercial building with refined proportions and premium cladding." },
  { id: 351, title: "Factory Design 1", category: "exterior", image: "/Website/Exterior/Factory 3d/4k__11 - Photo.jpg", description: "Industrial factory design with functional layout and modern aesthetic." },
  { id: 352, title: "Factory Design 2", category: "exterior", image: "/Website/Exterior/Factory 3d/4k__12 - Photo.jpg", description: "Factory exterior with efficient design and quality material finishes." },
  { id: 353, title: "Factory Design 3", category: "exterior", image: "/Website/Exterior/Factory 3d/4k__13 - Photo.jpg", description: "Factory design with contemporary industrial aesthetic and refined detailing." },
  { id: 354, title: "Factory Design 4", category: "exterior", image: "/Website/Exterior/Factory 3d/4K_14.jpg", description: "Factory exterior with modern facade treatment and premium cladding." },
  { id: 355, title: "Hospital Exterior 1", category: "exterior", image: "/Website/Exterior/Hospital Exterior 3d/hospital wire frame v-1  -op-2.jpg", description: "Hospital exterior with clean design and functional facade treatment." },
  { id: 356, title: "Hospital Exterior 2", category: "exterior", image: "/Website/Exterior/Hospital Exterior 3d/hospital wire frame v-1 -1.jpg", description: "Hospital exterior with modern aesthetic and quality material finishes." },
  { id: 357, title: "Hospital Exterior 3", category: "exterior", image: "/Website/Exterior/Hospital Exterior 3d/hospital wire frame v-2 -2.jpg", description: "Hospital exterior with refined proportions and contemporary design." },
  { id: 358, title: "Hospital Exterior 4", category: "exterior", image: "/Website/Exterior/Hospital Exterior 3d/hospital wire frame v-2 -3.jpg", description: "Hospital exterior with elegant facade and sophisticated detailing." },
  { id: 359, title: "Hospital Exterior 5", category: "exterior", image: "/Website/Exterior/Hospital Exterior 3d/hospital wire frame v-2 op-2.jpg", description: "Hospital exterior with functional design and premium cladding." },
  { id: 360, title: "Hospital Exterior 6", category: "exterior", image: "/Website/Exterior/Hospital Exterior 3d/hospital wire frame v-3- op-2.jpg", description: "Hospital exterior with contemporary styling and quality finishes." },
  { id: 361, title: "Hospital Exterior 7", category: "exterior", image: "/Website/Exterior/Hospital Exterior 3d/IMG_5217.jpg", description: "Hospital exterior render with photorealistic detail and modern design." },
  { id: 362, title: "Hospital Exterior 8", category: "exterior", image: "/Website/Exterior/Hospital Exterior 3d/IMG_5218.jpg", description: "Hospital exterior with refined facade and premium material palette." },
  { id: 363, title: "Hospital Exterior 9", category: "exterior", image: "/Website/Exterior/Hospital Exterior 3d/IMG_5219.jpg", description: "Hospital exterior with elegant proportions and contemporary aesthetic." },
  { id: 364, title: "Landscape Design 1", category: "exterior", image: "/Website/Exterior/Land scape/Land scape (1).JPG", description: "Landscape design with lush greenery and elegant outdoor spaces." },
  { id: 365, title: "Landscape Design 2", category: "exterior", image: "/Website/Exterior/Land scape/Land scape (2).JPG", description: "Landscape design with curated planting and premium outdoor finishes." },
  { id: 366, title: "Landscape Design 3", category: "exterior", image: "/Website/Exterior/Land scape/Land scape (3).jpg", description: "Landscape design with functional layout and refined aesthetic." },
  { id: 367, title: "Landscape Design 4", category: "exterior", image: "/Website/Exterior/Land scape/Land scape (4).JPG", description: "Landscape design with harmonious outdoor composition and quality materials." },
  { id: 368, title: "Landscape Design 5", category: "exterior", image: "/Website/Exterior/Land scape/Land scape (5).jpg", description: "Landscape design with natural materials and elegant outdoor styling." },
  { id: 369, title: "Landscape Design 6", category: "exterior", image: "/Website/Exterior/Land scape/Land scape (6).JPG", description: "Landscape design with integrated water features and curated planting." },
  { id: 370, title: "Temple Design 1", category: "exterior", image: "/Website/Exterior/Temple 3d/mandir (1).jpg", description: "Temple design with traditional architectural elements and sacred aesthetic." },
  { id: 371, title: "Temple Design 2", category: "exterior", image: "/Website/Exterior/Temple 3d/mandir (2).jpg", description: "Temple design with intricate detailing and premium stone finishes." },
  { id: 372, title: "Temple Design 3", category: "exterior", image: "/Website/Exterior/Temple 3d/mandir (3).jpg", description: "Temple design with classical proportions and refined craftsmanship." },
  { id: 373, title: "Temple Design 4", category: "exterior", image: "/Website/Exterior/Temple 3d/mandir (4).jpg", description: "Temple design with elegant facade and traditional material palette." },
  { id: 374, title: "Township Development 2", category: "exterior", image: "/Website/Exterior/Township/site presentation (2).jpg", description: "Township development with integrated amenities and modern planning." },
  { id: 375, title: "Township Development 3", category: "exterior", image: "/Website/Exterior/Township/site presentation (3).jpg", description: "Township development with residential clusters and quality landscaping." },
  { id: 376, title: "Township Development 4", category: "exterior", image: "/Website/Exterior/Township/site presentation (4).jpg", description: "Township development with community spaces and refined site planning." },
  { id: 377, title: "Township Development 5", category: "exterior", image: "/Website/Exterior/Township/site presentation (5).jpg", description: "Township development with premium amenities and cohesive master plan." },
  { id: 378, title: "Township Development 6", category: "exterior", image: "/Website/Exterior/Township/site presentation (6).jpg", description: "Township development with elegant residential design and quality finishes." },
  { id: 379, title: "University Campus 2", category: "exterior", image: "/Website/Exterior/University/view 2.jpg", description: "University campus with modern architecture and functional landscape." },
  { id: 380, title: "University Campus 3", category: "exterior", image: "/Website/Exterior/University/view 3.jpg", description: "University campus with contemporary design and quality exterior finishes." },
  { id: 381, title: "University Campus 4", category: "exterior", image: "/Website/Exterior/University/view 4.jpg", description: "University campus with refined facade and cohesive architectural language." },
  { id: 382, title: "University Campus 5", category: "exterior", image: "/Website/Exterior/University/view 5.jpg", description: "University campus with elegant proportions and premium material palette." },
  { id: 383, title: "University Campus 6", category: "exterior", image: "/Website/Exterior/University/view 6.jpg", description: "University campus with modern aesthetic and sophisticated detailing." },
  { id: 384, title: "University Campus 7", category: "exterior", image: "/Website/Exterior/University/view 7.jpg", description: "University campus with grand scale design and quality architectural finishes." },
  { id: 385, title: "University Campus 8", category: "exterior", image: "/Website/Exterior/University/view 8.jpg", description: "University campus with contemporary facade and integrated landscaping." },
  { id: 386, title: "University Campus 9", category: "exterior", image: "/Website/Exterior/University/view 10.jpg", description: "University campus with refined design and premium exterior material choices." },
];

// ─── Walkthroughs ─────────────────────────────────────────────────────────────
export const WALKTHROUGHS = [
  {
    id: 1,
    title: "Commercial Building Walkthrough",
    src: "/Walk through 1.mp4",
    description: "A cinematic exterior and interior tour of a premium commercial building design.",
    category: "commercial",
  },
  {
    id: 2,
    title: "Home Interior Tour",
    src: "/Walk through 2.mp4",
    description: "A detailed walkthrough of a beautifully designed residential interior.",
    category: "residential",
  },
  {
    id: 3,
    title: "University Campus Exterior",
    src: "/Walk through 3.mp4",
    description: "An architectural walkthrough of a university campus exterior and landscape design.",
    category: "exterior",
  },
  {
    id: 4,
    title: "Home Interior Showcase",
    src: "/Walk through 4.mp4",
    description: "A stunning walkthrough of a modern home interior with premium finishes.",
    category: "residential",
  },
];

// ─── Stats ────────────────────────────────────────────────────────────────────
export const STATS = [
  { value: 200, suffix: "+", label: "Projects Completed" },
  { value: 8, suffix: "+", label: "Years of Experience" },
  { value: 150, suffix: "+", label: "Happy Clients" },
];

// ─── Testimonials ─────────────────────────────────────────────────────────────
export const TESTIMONIALS = [
  {
    id: 1,
    name: "Rajesh Mehta",
    location: "Ahmedabad, Gujarat",
    text: "Devnandan Interiors transformed our home completely. The 3D visualization helped us understand exactly what the final result would look like before any work began. Absolutely thrilled with the outcome!",
    rating: 5,
  },
  {
    id: 2,
    name: "Priya Sharma",
    location: "Bopal, Ahmedabad",
    text: "Professional team, incredible designs, and delivered on time. Our modular kitchen looks exactly like the 3D render they showed us. Highly recommend to anyone planning a renovation!",
    rating: 5,
  },
  {
    id: 3,
    name: "Ankit Patel",
    location: "Surat, Gujarat",
    text: "We hired them for our office redesign and the results exceeded expectations. The team understood our requirements and delivered a functional, beautiful workspace our entire team loves.",
    rating: 5,
  },
  {
    id: 4,
    name: "Sneha Joshi",
    location: "Gandhinagar, Gujarat",
    text: "The 3D walkthrough they created for our villa project was stunning. It made every design decision so easy and clear. Their attention to detail is truly unmatched.",
    rating: 5,
  },
  {
    id: 5,
    name: "Vikram Desai",
    location: "Vadodara, Gujarat",
    text: "From concept to completion, Devnandan Interiors maintained excellent communication and delivered a jewellery showroom design that our customers absolutely love walking into.",
    rating: 5,
  },
];

// ─── FAQ ──────────────────────────────────────────────────────────────────────
export const FAQ_ITEMS = [
  {
    id: 1,
    question: "What areas do you serve?",
    answer: "We primarily serve Ahmedabad and surrounding Gujarat regions, including Surat, Vadodara, and Gandhinagar. We also take on projects across India for clients requiring 3D visualization and design services remotely.",
  },
  {
    id: 2,
    question: "Do you provide 3D visualization before work begins?",
    answer: "Yes — 3D visualization is at the core of our process. We create photorealistic renders and animated walkthroughs so you can experience your space before a single brick is laid. No surprises, only confidence.",
  },
  {
    id: 3,
    question: "How long does a typical interior design project take?",
    answer: "Project timelines vary by scope. A single room typically takes 2–4 weeks for design and renders. A full home project runs 6–12 weeks from concept to final render. Construction timelines depend on your contractor.",
  },
  {
    id: 4,
    question: "What is your pricing model?",
    answer: "We offer flexible pricing based on project size and requirements. Contact us with your project details and we'll provide a customized quote. We have packages for both residential and commercial projects at various budget levels.",
  },
  {
    id: 5,
    question: "Can I request changes after seeing the 3D renders?",
    answer: "Absolutely. That's exactly the purpose of the render stage — to allow revisions before any physical work begins. We offer multiple revision rounds to ensure you're completely satisfied with the design.",
  },
  {
    id: 6,
    question: "Do you handle modular kitchen and wardrobe design?",
    answer: "Yes, we specialize in modular furniture design including kitchens, wardrobes, TV units, and study areas. We provide detailed 3D previews with your exact dimensions and finish choices before manufacturing.",
  },
];
